# Generated by Django 4.1.2 on 2022-10-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_mydata_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Created_by',
        ),
    ]
