# Generated by Django 4.1.2 on 2022-10-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_department_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='department',
            name='Name',
            field=models.CharField(max_length=50),
        ),
    ]
