# Generated by Django 4.1.2 on 2022-10-05 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_remove_department_created_by'),
        ('authentication', '0002_useraccount_created_by_useraccount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.department'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
