# Generated by Django 4.1.2 on 2022-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_department_description_alter_department_name'),
        ('authentication', '0004_remove_useraccount_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='department',
            field=models.ForeignKey(null=True, on_delete=models.SET('deleted'), to='admins.department'),
        ),
    ]
