# Generated by Django 4.1.2 on 2022-10-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='userid',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
