# Generated by Django 4.1.2 on 2022-10-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_ticket_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
